### ISSUE TITLE
Incorrect output with small program

### ISSUE THREAD

**Issue by wheelerlaw** [rwtodd/Go.Sed#1]
Simple usage of GNU sed v4.4 on Ubuntu 18.04:

```
$ echo hello | sed 's|hello|world|'
world
```

However, go-sed keeps returning an empty string:

![image](https://user-images.githubusercontent.com/3081566/43981916-d1dec01e-9cc1-11e8-8e78-5e3354c65c34.png)

**Comment by rwtodd** [comment]
Looking at your screenshot it looks like you want "sed.New" instead of "sed.NewQuiet".  The quiet version is equivalent to running sed with "-n".   So if your script has no 'p' commands there will be no output for quiet engines.

**Comment by wheelerlaw** [comment]
You're totally right. Changes it to using `sed.New` and it worked without a hitch. Thanks!
