### ISSUE TITLE
How do I write GNU sed equivalent for this?

### ISSUE THREAD

**Issue by shadyabhi** [rwtodd/Go.Sed#2]
Hi,

```
➤ echo '200' | sed 's/\(.\).*/\1xx/'
2xx
➤ echo '200' | sed-go 's/(.)../$1 xx/'
2 xx
➤ echo '200' | sed-go 's/(.)../$1xx/'

➤
```
How do I write an expression such that I don't have a space between `2` and `xx`? If I remote the space, it doesn't seem to work. 

Thanks in advance!

**Comment by rwtodd** [comment]
With braces.  That's a quirk of go's regexp library, and nothing specific to sed-go. So:

    echo '200' | sed-go 's/(.)../${1}xx/'
    2xx

**Comment by shadyabhi** [comment]
Thank you.
