### ISSUE TITLE
build / install instructions

### ISSUE THREAD

**Issue by mralusw** [rwtodd/Go.Sed#3]
... would be nice to have. Something like `cd cmd/sed-go && go build`, at least.

**Comment by rwtodd** [comment]
It's an interesting suggestion.  I hope there are not many people who are both (1) interested in sed-go, and also (2) don't know how to build a go project. If it ever got that popular I would take the repo private rather than support it 🤣

**Comment by mralusw** [comment]
No, but there are people interested in **sed** who may not want to go through this
```
$ go build
no Go files in ...
# find out where the module is
$ go build cmd/sed-go
package cmd/sed-go is not in GOROOT
$ go build ./cmd/sed-go
```

**Comment by rwtodd** [comment]
Ok, I've added a comment to the README and removed the `go get` instructions since I think that is deprecated now.  Thanks again for the suggestion.
