### ISSUE TITLE
Parameter -i for in-place file changes is missing

### ISSUE THREAD

**Issue by systemstart** [rwtodd/Go.Sed#8]
Hi.

This doesn't support the sed parameter -i to changes files in-place, I did a rough implementation of that under systemstart/go-sed@bb8ed5da0fd0e2aa0d9a46bbbc35a5e399c62e00

It's only manually tested and I would aim for writing tests, but for that I would move much logic from `cmd/go-sed/main.go` to `sed/`

This would mean even more changes, let me hear what you think of all this before I spend more blood, sweat and tears ;)

Cheers,

Alexander

**Comment by rwtodd** [comment]
First of all sorry I didn't see this for two weeks. 

Though I think most 'sed's in the wild take an extension argument and back up the original, I don't mind adding a more basic in-place update.  I've pulled it, thanks!  If you want to refine it or whatever, just let me know and I'll pull that too.

As for arranging to add tests (I assume to test that the UIDs and permissions get set correctly?) if you are willing to put in that much work I'm sure we can find a way to arrange the code.  Really I wrote it to use as a library, and the driver program was just to demonstrate it, but if you are wanting to flesh out the functionality of the driver program I would pull anything that's roughly compatible with what someone would expect from a system `sed`.   Be aware that I haven't been coding in Go for a few years, so I won't be active in this repo.

I'm glad people like this project, though.  It was fun to do.
